/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package king.of.ta3meer;

import java.sql.Connection;
import java.util.Date;  
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Types;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kamal
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public ArrayList<String> brand ;
    public ArrayList<String> country ;
    public ArrayList<String> kinds ;
    public int user_id ;
    
    public AddProduct(ArrayList<String> brand,ArrayList<String> country,ArrayList<String> kinds,int usr) {
        this.brand=new ArrayList<>();
        this.brand=brand;
        this.country =new ArrayList<>();
        this.country = country;
        this.kinds =new ArrayList<>();
        this.kinds = kinds;
        this.user_id=usr;

        initComponents();
        for (String kind : this.kinds) {
            this.jKind.addItem(kind);
        }
        for (String coun : this.country) {
            this.jCountry.addItem(coun);
        }
        for (String brd : this.brand) {
            this.jBrand.addItem(brd);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        P_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBrand = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCountry = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jKind = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 0, 64));
        jPanel1.setForeground(new java.awt.Color(154, 6, 128));

        P_name.setBackground(new java.awt.Color(121, 1, 140));
        P_name.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        P_name.setForeground(new java.awt.Color(255, 255, 255));
        P_name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        P_name.setToolTipText("");
        P_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_nameActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(22, 0, 64));
        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 6, 128));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("أسم المنتج");

        jLabel2.setBackground(new java.awt.Color(22, 0, 64));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(154, 6, 128));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("الكمية");

        Quantity.setBackground(new java.awt.Color(121, 1, 140));
        Quantity.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        Quantity.setForeground(new java.awt.Color(255, 255, 255));
        Quantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Quantity.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(22, 0, 64));
        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(154, 6, 128));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("السعر");

        Price.setBackground(new java.awt.Color(121, 1, 140));
        Price.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Price.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(22, 0, 64));
        jLabel4.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(154, 6, 128));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("النوع");

        jBrand.setBackground(new java.awt.Color(121, 1, 140));
        jBrand.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jBrand.setForeground(new java.awt.Color(154, 6, 128));

        jLabel5.setBackground(new java.awt.Color(22, 0, 64));
        jLabel5.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 6, 128));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("بلد الصنع");

        jCountry.setBackground(new java.awt.Color(121, 1, 140));
        jCountry.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jCountry.setForeground(new java.awt.Color(154, 6, 128));

        jLabel6.setBackground(new java.awt.Color(22, 0, 64));
        jLabel6.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(154, 6, 128));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("تصنيف");

        jKind.setBackground(new java.awt.Color(121, 1, 140));
        jKind.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jKind.setForeground(new java.awt.Color(154, 6, 128));

        jButton1.setBackground(new java.awt.Color(154, 6, 128));
        jButton1.setFont(new java.awt.Font("Aldhabi", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(22, 0, 64));
        jButton1.setText("اضافة");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jKind, javax.swing.GroupLayout.Alignment.TRAILING, 0, 336, Short.MAX_VALUE)
                    .addComponent(P_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Price)
                    .addComponent(Quantity)
                    .addComponent(jBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DBConnect connection = new DBConnect();
        
        Connection conn1 =connection.connect();//main table
        //Connection conn2 =connection.connect();
        PreparedStatement stmt1;
        Statement stmt2;
        String p_name = P_name.getText();
        float price = Float.valueOf(Price.getText());
        int quantity = Integer.valueOf(Quantity.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");  
        Date date = new Date();
        String Dt = formatter.format(date);
        int id = this.user_id;
        int b_id ;
        int c_id;
        int k_id;
        try {
            //geting ids
            stmt2=conn1.createStatement();
            
            String q1="Select id from brand where brand ='"+jBrand.getSelectedItem()+"'";
            ResultSet rs    = stmt2.executeQuery(q1);
            
            if(rs.next()){
             b_id= rs.getInt("id");//brand  
             //
            }else{
                b_id= jBrand.getSelectedIndex();
            }
            
            q1="Select id from countries where country_name ='"+jCountry.getSelectedItem()+"'";
            rs    = stmt2.executeQuery(q1);
            
            if(rs.next()){
              c_id= rs.getInt("id");//country    
            }else{
                c_id =jCountry.getSelectedIndex();
            }
            
            q1="Select id from kinds where kind ='"+jKind.getSelectedItem()+"'";
            rs    = stmt2.executeQuery(q1);
            
            if(rs.next()){
             k_id= rs.getInt("id");//kind
             
            }else{
              k_id=jKind.getSelectedIndex();
            }
            
            //finished getting ids
            
            
            //conn1 =connection.connect();
            String query = "Insert Into store (product_name,quantity,price,brand_id,country_id,Last_update,updatedby_id,kind) VALUES(?,?,?,?,?,?,?,?)";
            stmt1 = conn1.prepareStatement(query); 
            stmt1.setString(1,p_name);
            stmt1.setInt(2, quantity);
            stmt1.setFloat(3, price);
            //to get ids
            stmt1.setInt(4, b_id);
            stmt1.setInt(5, c_id);
            stmt1.setString(6, Dt);
            stmt1.setInt(7,id);//id
            stmt1.setInt(8, k_id);
            stmt1.executeUpdate();
            stmt1.close();
            connection.close(conn1);
            stmt2.close();
            JFrame x = new JFrame();
            x.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(x, "تمت الأضافة بنجاح !");
            P_name.setText("");
            Price.setText("");
            Quantity.setText("");
        }catch(Exception e){
            System.out.println(e);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P_name;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JComboBox<String> jBrand;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCountry;
    private javax.swing.JComboBox<String> jKind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
