/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package king.of.ta3meer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author kamal
 */
public class buyProduct extends javax.swing.JFrame {

    /**
     * Creates new form buyProduct
     */
    public ArrayList<Integer> p_ids ;
    public ArrayList<Integer> quantity ;
    public ArrayList<String> products ;
    public ArrayList<Double> prices ;
    public Invoices v;
    public buyProduct(Invoices inv) {
        
        this.v =inv;
        this.p_ids = new ArrayList<>();
        this.prices = new ArrayList<>();
        this.products =new ArrayList<>();
        this.quantity=new ArrayList<>();
        try {
        DBConnect connection = new DBConnect();
        
        Connection conn1 =connection.connect();//main table
        
        Statement stmt1;
        stmt1 = conn1.createStatement();
        String query = "select id , product_name ,price ,quantity from store";
        ResultSet rs    = stmt1.executeQuery(query);
        
            while(rs.next()){
                p_ids.add(rs.getInt("id"));
                products.add(rs.getString("product_name"));
                prices.add(rs.getDouble("price"));
                quantity.add(rs.getInt("quantity"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(buyProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        initComponents();
        for (String product : this.products) {
            this.jProduct.addItem(product);
        }
        this.lable_avail.setText("الكميـة المتوفرة :"+String.valueOf(this.quantity.get(this.products.indexOf(this.jProduct.getSelectedItem()))));
        this.Price.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jProduct = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Quantity = new javax.swing.JTextField();
        lable_avail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 28, 50));
        jPanel1.setForeground(new java.awt.Color(236, 179, 101));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(142, 128, 106));
        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("أسم المنتج");

        jLabel2.setBackground(new java.awt.Color(142, 128, 106));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("الكمية");

        jLabel3.setBackground(new java.awt.Color(142, 128, 106));
        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("السعر");

        Price.setBackground(new java.awt.Color(255, 230, 188));
        Price.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        Price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price.setEnabled(false);

        jProduct.setBackground(new java.awt.Color(142, 128, 106));
        jProduct.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jProduct.setForeground(new java.awt.Color(228, 205, 167));
        jProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jProduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jProductItemStateChanged(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(236, 179, 101));
        jButton1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("اضافة");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Quantity.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        Quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Quantity.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                QuantityCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                QuantityInputMethodTextChanged(evt);
            }
        });
        Quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityKeyTyped(evt);
            }
        });

        lable_avail.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        lable_avail.setForeground(new java.awt.Color(255, 255, 255));
        lable_avail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lable_avail.setText("المتوفر");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lable_avail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Price)
                    .addComponent(jProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(Quantity))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_avail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DBConnect connection = new DBConnect();

        Connection conn1 =connection.connect();//main table
        
        PreparedStatement stmt1;
        Statement stmt2;
        JFrame x = new JFrame();
        x.setAlwaysOnTop(true);
        double total_cost = -1;//totalcost
        //int quantity = Integer.valueOf(Quantity.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String Dt = formatter.format(date);//date
        int usr_id = this.v.main.usr.id;//sellerid
        int p_id =this.p_ids.get(this.products.indexOf(this.jProduct.getSelectedItem()));//product id
        //invoice_id
        int inv_id=0;
        int quant =-1;
        try {
            
            conn1 =connection.connect();
            
            String q1="Select id from invoices where state=0 and total=0 LIMIT 1";
            
            stmt2 = conn1.createStatement();
            
            ResultSet rs    = stmt2.executeQuery(q1);
            
            if(rs.next()){
                inv_id = rs.getInt("id");
            }
            //
            q1="Select * from invoice_details where invoices_id="+inv_id+" and product_id="+p_id+" LIMIT 1";
            
            stmt2 = conn1.createStatement();
            rs    = stmt2.executeQuery(q1);
            
            
            q1="Select quantity from store where id="+p_id;
            stmt2 = conn1.createStatement();
            ResultSet r1 =stmt2.executeQuery(q1);
            if(rs.next() && !"".equals(this.Quantity.getText())){
                //check quantity validity
            quant =Integer.valueOf(this.Quantity.getText());
            total_cost=this.prices.get(this.products.indexOf(this.jProduct.getSelectedItem()))*Integer.valueOf(this.Quantity.getText());
                if(r1.next() && r1.getInt("quantity")>=(quant+rs.getInt("quantity"))){
                    
                
                
                
                
                
                
                //in case the row already exists
                q1="Update invoice_details set quantity= ? , total_cost=? where invoices_id=? and product_id=?";
                stmt1 = conn1.prepareStatement(q1);
                stmt1.setInt(1,quant+rs.getInt("quantity"));
                stmt1.setDouble(2, total_cost+rs.getDouble("total_cost"));
                stmt1.setInt(3, inv_id);
                stmt1.setInt(4,p_id);
                stmt1.executeUpdate();
                stmt1.close();
                JOptionPane.showMessageDialog(x, "تمت الأضافة للفاتورة بنجاح! !"); 
                }
                else{
                   JOptionPane.showMessageDialog(x, "الكمية المتاحة لا تكفي من فضلك اطلب كمية اقل  بحد أقصى لهذا المنتج "+r1.getInt("quantity")); 
                }
               
            }else{
            if(!"".equals(this.Quantity.getText())){
            quant =Integer.valueOf(this.Quantity.getText());
            total_cost=this.prices.get(this.products.indexOf(this.jProduct.getSelectedItem()))*Integer.valueOf(this.Quantity.getText());
            if(r1.next() && r1.getInt("quantity")>=quant){
            
            String query = "Insert Into invoice_details (invoices_id,product_id,quantity,total_cost) VALUES(?,?,?,?)";
            
            stmt1 = conn1.prepareStatement(query);
            stmt1.setInt(1,inv_id);
            stmt1.setInt(2, p_id);
            stmt1.setInt(3, quant);
            stmt1.setDouble(4, total_cost);
            stmt1.executeUpdate();
            stmt1.close();
            JOptionPane.showMessageDialog(x, "تمت الأضافة للفاتورة بنجاح! !");
            }else{
                JOptionPane.showMessageDialog(x, "الكمية المتاحة لا تكفي من فضلك اطلب كمية اقل  بحد أقصى لهذا المنتج "+r1.getInt("quantity")); 
            }
            }
            
            }
            
            
            
            stmt2.close();
            connection.close(conn1);
        }catch(Exception e){
            System.out.println(e);
        }

        //fill table
        v.fillTable();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jProductItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jProductItemStateChanged
        // TODO add your handling code here:
        this.lable_avail.setText("الكميـة المتوفرة :"+String.valueOf(this.quantity.get(this.products.indexOf(this.jProduct.getSelectedItem()))));
        this.Price.setText("0");
        
        
        
    }//GEN-LAST:event_jProductItemStateChanged

    private void QuantityInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_QuantityInputMethodTextChanged

        //this.Price.setText(String.valueOf(this.prices.get(this.products.indexOf(this.jProduct.getSelectedItem()))*Integer.valueOf(this.Price1.getText())));


        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityInputMethodTextChanged

    private void QuantityCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_QuantityCaretPositionChanged

        //this.Price.setText(String.valueOf(this.prices.get(this.products.indexOf(this.jProduct.getSelectedItem()))*Integer.valueOf(this.Price1.getText())));

        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityCaretPositionChanged

    private void QuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyTyped
       if(!"".equals(this.Quantity.getText())){
           try{
        if(Integer.valueOf(this.Quantity.getText())>0 && Integer.valueOf(this.Quantity.getText())<=this.quantity.get(this.products.indexOf(this.jProduct.getSelectedItem()))){
        this.Price.setText(String.valueOf(this.prices.get(this.products.indexOf(this.jProduct.getSelectedItem()))*Integer.valueOf(this.Quantity.getText())));
          }else{
            this.Price.setText("0");
        }
           }catch(Exception e){
               JFrame x = new JFrame();
               x.setAlwaysOnTop(true);
               JOptionPane.showMessageDialog(x, "من فضلك دخل رقم مكان الكمية يكون أقل من أقصى عدد للكمية علشان نحسبلك التكلفة !","رسالة تأكيد",1);
           }
       }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new buyProduct().setVisible(true);
            }
        });

*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jProduct;
    private javax.swing.JLabel lable_avail;
    // End of variables declaration//GEN-END:variables
}
