/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package king.of.ta3meer;

import com.sun.glass.events.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kamal
 */
public class Invoices extends javax.swing.JFrame {

    /**
     * Creates new form Invoices
     */
    public MainFrame main ;
    public int inv_id;
    public Invoices(MainFrame m) throws SQLException {
        initComponents();
        this.main = m;
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String Dt = formatter.format(date);
        this.date_time.setText(Dt);
        this.jSeller.setText(m.usr.Username);
        String q1="Select id from invoices where state=0 and total=0 LIMIT 1";
        DBConnect connection = new DBConnect();

        Connection conn1 =connection.connect();    
       
        Statement stmt2 = conn1.createStatement();
            
            
        ResultSet rs    = stmt2.executeQuery(q1);
            
        if(rs.next()){
                this.inv_id = rs.getInt("id");
        }
        connection.close(conn1);
        stmt2.close();
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTotal = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jClient = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date_time = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeller = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(15, 4, 76));
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(236, 179, 101));

        data.setBackground(new java.awt.Color(4, 28, 50));
        data.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        data.setForeground(new java.awt.Color(236, 179, 101));
        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "القيمة الأجمالية", "سعر الوحدة", "الكمية أو العدد", "أسم المنتج"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        data.setToolTipText("");
        data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data.setGridColor(new java.awt.Color(6, 70, 99));
        data.setIntercellSpacing(new java.awt.Dimension(0, 0));
        data.setName(""); // NOI18N
        data.setSelectionBackground(new java.awt.Color(236, 179, 101));
        data.setSelectionForeground(new java.awt.Color(4, 28, 50));
        data.setShowVerticalLines(false);
        data.getTableHeader().setReorderingAllowed(false);
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dataMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        jButton1.setBackground(new java.awt.Color(4, 41, 58));
        jButton1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("اضافة منتج");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(4, 41, 58));
        jButton2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("حذف منتج");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTotal.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTotal.setText("الاجمالي");

        jButton4.setBackground(new java.awt.Color(4, 41, 58));
        jButton4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("حساب الأجمالي");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(4, 41, 58));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("قفل الفاتورة");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271)
                        .addComponent(jButton4)
                        .addGap(28, 28, 28)
                        .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 730, 550));

        jPanel2.setBackground(new java.awt.Color(4, 28, 50));

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("اسم العميل*");

        jClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("التاريخ");

        date_time.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        date_time.setForeground(new java.awt.Color(255, 255, 255));
        date_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date_time.setText("00-00-2021");

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("مسؤول المبيعات");

        jSeller.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jSeller.setForeground(new java.awt.Color(255, 255, 255));
        jSeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSeller.setText("هاجر");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_time, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClient, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 1, 390, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!"".equals(jClient.getText())){
            new buyProduct(this).setVisible(true);
        }else{
            JFrame x = new JFrame();
            x.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(x, "من فضلك أدخل أسم العميل أولا!","رسالة تأكيد",1);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //this.data.getSelectedRow();
       DBConnect connection = new DBConnect();
        
       Connection conn1 =connection.connect();
       
       //System.out.println(data.getValueAt(data.getSelectedRow(),7));
       int inv_id=-1;
        
        JFrame x = new JFrame();
        x.setAlwaysOnTop(true);
        if(data.getSelectedRow()!=-1){
        int confirmation =JOptionPane.showConfirmDialog(x, "هل أنت متأكد من أنك تريد حذف العنصر ؟","رسالة تأكيد",YES_NO_OPTION);
        if(confirmation==0){
        try {
            //get_inv id
            //conn1 =connection.connect();
            
            String q1="Select id from invoices where state=0 and total=0 LIMIT 1";
            
            Statement stmt2 = conn1.createStatement();
            
            ResultSet rs    = stmt2.executeQuery(q1);
            
            if(rs.next()){
                inv_id = rs.getInt("id");
            }
                 
            String query ="Delete from invoice_details where invoices_id ="+inv_id+" and product_id = "+data.getValueAt(data.getSelectedRow(),0);
            stmt2 = conn1.createStatement();
            stmt2.executeUpdate(query);
            connection.close(conn1);
            stmt2.close();
            this.fillTable();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }else{
            //do nothing
        }
        }else{
            JOptionPane.showMessageDialog(rootPane,"من فضلك أختر صف !");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        double total=0;
        String tmp=new String();
        
        for(int i=0;i<data.getRowCount();i++){
            tmp =String.valueOf(data.getValueAt(i,4));
            total+=Double.valueOf(tmp);
        }
        this.jTotal.setText(String.valueOf(total));
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        DBConnect connection = new DBConnect();
        
        Connection conn1 =connection.connect();
        
        
        String sql="Update invoices set state =?,"
                + "client_name= ?,"
                + "total= ?"
                + "where id =?";
        
        try {
            PreparedStatement pstmt = conn1.prepareStatement(sql);
                
            pstmt.setInt(1,1);
            if(!"".equals(jClient.getText())){
                pstmt.setString(2,jClient.getText());
            }else{
                pstmt.setString(2,"عميل");
            }
            //total
            double total=0;
            String tmp=new String();
            for(int i=0;i<data.getRowCount();i++){
            tmp =String.valueOf(data.getValueAt(i,4));
            total+=Double.valueOf(tmp);
            }
            
            pstmt.setDouble(3,total);
            
            pstmt.setInt(4,this.inv_id);        
                    
            pstmt.executeUpdate();
            pstmt.close();
            connection.close(conn1);        
            
            Statement stmt = conn1.createStatement();
            ResultSet rs   ; 
            //quantites
            for(int i=0;i<this.data.getRowCount();i++){
                //
               conn1 =connection.connect();
               stmt = conn1.createStatement();
               int id = Integer.valueOf(String.valueOf(data.getValueAt(i,0)));
               int quantity = Integer.valueOf(String.valueOf(data.getValueAt(i,2)));
               
               String q = "select quantity from store where id="+id;
               rs = stmt.executeQuery(q);
               if(rs.next()){
                   quantity = rs.getInt("quantity") - quantity ;
               }
               
               sql = "update store set quantity = ? where id =?";
               pstmt = conn1.prepareStatement(sql);
               pstmt.setInt(1,quantity); 
               pstmt.setInt(2,id);
               pstmt.executeUpdate();
               pstmt.close();
               connection.close(conn1);
                
            }
            pstmt.close();
            connection.close(conn1);
 
            
            JFrame x = new JFrame();
            x.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(x, "تم قفل الفاتورة بنجاح !");      
            this.main.setVisible(true);
            this.dispose();
      
                    } catch (SQLException ex) {
            Logger.getLogger(Invoices.class.getName()).log(Level.SEVERE, null, ex);
        }
        main.showInvoices();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        // TODO add your handling code here:
        System.out.println(data.getValueAt(data.getSelectedRow(), data.getSelectedColumn()));
   
    }//GEN-LAST:event_dataMouseClicked

    private void dataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseReleased
        // TODO add your handling code here:
        System.out.println(data.getValueAt(data.getSelectedRow(), data.getSelectedColumn()));

    }//GEN-LAST:event_dataMouseReleased

    /**
     * @param args the command line arguments
     */
    
    public void fillTable(){
        //table setting
        DBConnect connection = new DBConnect();
        
        Connection conn1 =connection.connect();
       
       
        Statement stmt2;

        int inv_id = 0;
        
       
       
       
       
        try {
                //get inv_id
            String q1="Select id from invoices where state=0 and total=0 LIMIT 1";
            
            stmt2 = conn1.createStatement();
            
            ResultSet rs    = stmt2.executeQuery(q1);
            
            if(rs.next()){
                inv_id = rs.getInt("id");
            }
            stmt2 = conn1.createStatement();    
            String query = "Select * from invoice_details where invoices_id ="+inv_id;      
   
            rs    = stmt2.executeQuery(query);
            
            DefaultTableModel d =new DefaultTableModel(){
                //to prevent users from changing the values inside the table ui
                public boolean isCellEditable(int row, int column) {
                return false;
             }
                
            };
            this.data.setModel(d);
            
            //"أسم المنتج", "الكمية المتواجدة", "سعر الوحدة", "نوع المنتج", "بلد التصنيع", "تاريخ أخر تعديل", "بواسطة"
            d.addColumn("رقم المنتج");
            d.addColumn("أسم المنتج");
            d.addColumn("الكمية أو العدد");
            d.addColumn("سعر الوحدة");
            d.addColumn("القيمة الأجمالية");

            //q1="Select product_name ,price from store where id ="
            ResultSet r;
            while(rs.next()){
                stmt2 = conn1.createStatement();
                q1="Select product_name ,price from store where id ="+rs.getInt("product_id")+" LIMIT 1";
                r =stmt2.executeQuery(q1);
                if(r.next()){
                d.addRow(new Object[]{
                rs.getInt("product_id"),
                r.getString("product_name"),
                rs.getInt("quantity"),
                r.getDouble("price"),
                rs.getDouble("total_cost"),
                });
                }
    
            }
            stmt2.close();
            connection.close(conn1);

            }catch (SQLException ex) {
               Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoices().setVisible(true);
            }
        });
*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data;
    private javax.swing.JLabel date_time;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jClient;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSeller;
    private javax.swing.JLabel jTotal;
    // End of variables declaration//GEN-END:variables
}
