/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package king.of.ta3meer;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import static com.itextpdf.text.pdf.BidiOrder.R;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Graphics2D;
import java.awt.print.PrinterJob;
import java.io.FileOutputStream;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static org.bouncycastle.crypto.params.Blake3Parameters.context;

/**
 *
 * @author kamal
 */
public class ShowInvoice extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public int invoice_id;
    public MainFrame main;
    
    public ShowInvoice(int inv_id ,MainFrame m) {
        this.invoice_id = inv_id;
        this.main = m;
        initComponents();
        
        //here we show
        DBConnect connection = new DBConnect();
        
        Connection conn1 =connection.connect();//main table
        
        String query = "Select date ,client_name,total from invoices where id = "+this.invoice_id;
        try {
            Statement stmt1=conn1.createStatement();
            ResultSet rs = stmt1.executeQuery(query);
            if(rs.next()){
            this.date_time.setText(rs.getString("date"));
            this.jTotal.setText(rs.getString("total")+"  جنيه");
            this.jSeller.setText(m.usr.Username);
            this.jClient.setText(rs.getString("client_name"));
            }
            connection.close(conn1);
            stmt1.close();
        } catch (SQLException ex) {
            Logger.getLogger(ShowInvoice.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        jTotal = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date_time = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeller = new javax.swing.JLabel();
        jClient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("تفاصيل الفاتورة");
        setLocation(new java.awt.Point(500, 300));
        setMinimumSize(new java.awt.Dimension(993, 410));
        setResizable(false);
        setSize(new java.awt.Dimension(993, 410));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(236, 179, 101));

        data.setBackground(new java.awt.Color(4, 28, 50));
        data.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        data.setForeground(new java.awt.Color(236, 179, 101));
        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "القيمة الأجمالية", "سعر الوحدة", "الكمية أو العدد", "أسم المنتج"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        data.setToolTipText("");
        data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data.setGridColor(new java.awt.Color(6, 70, 99));
        data.setIntercellSpacing(new java.awt.Dimension(0, 0));
        data.setName(""); // NOI18N
        data.setSelectionBackground(new java.awt.Color(236, 179, 101));
        data.setSelectionForeground(new java.awt.Color(4, 28, 50));
        data.setShowVerticalLines(false);
        data.getTableHeader().setReorderingAllowed(false);
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dataMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        jTotal.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal.setText("الاجمالي");

        jButton5.setBackground(new java.awt.Color(4, 41, 58));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("قفل الفاتورة");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 720, 380));

        jPanel2.setBackground(new java.awt.Color(4, 28, 50));

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("اسم العميل*");

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("التاريخ");

        date_time.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        date_time.setForeground(new java.awt.Color(255, 255, 255));
        date_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date_time.setText("00-00-2021");

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("مسؤول المبيعات");

        jSeller.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jSeller.setForeground(new java.awt.Color(255, 255, 255));
        jSeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSeller.setText("هاجر");

        jClient.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jClient.setForeground(new java.awt.Color(255, 255, 255));
        jClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jClient.setText("هاجر");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_time, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 1, 390, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        // TODO add your handling code here:
        System.out.println(data.getValueAt(data.getSelectedRow(), data.getSelectedColumn()));

    }//GEN-LAST:event_dataMouseClicked

    private void dataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseReleased
        // TODO add your handling code here:
        System.out.println(data.getValueAt(data.getSelectedRow(), data.getSelectedColumn()));
    }//GEN-LAST:event_dataMouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

            JFrame x = new JFrame();
            x.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(x, "تم قفل الفاتورة بنجاح !");
            this.main.setVisible(true);
            this.dispose();
            main.showInvoices();

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowInvoice().setVisible(true);
            }
        });
*/
    }
    
    public void fillTable(){
        //table setting
        DBConnect connection = new DBConnect();
        
        Connection conn1 =connection.connect();
        String q1;
       
        Statement stmt2;
        ResultSet rs;
        
        
       
       
       
       
        try {
            
            
            stmt2 = conn1.createStatement();    
            String query = "Select * from invoice_details where invoices_id ="+this.invoice_id;      
   
            rs    = stmt2.executeQuery(query);
            
            DefaultTableModel d =new DefaultTableModel(){
                //to prevent users from changing the values inside the table ui
                public boolean isCellEditable(int row, int column) {
                return false;
             }
                
            };
            this.data.setModel(d);
            
            //"أسم المنتج", "الكمية المتواجدة", "سعر الوحدة", "نوع المنتج", "بلد التصنيع", "تاريخ أخر تعديل", "بواسطة"
            d.addColumn("رقم المنتج");
            d.addColumn("أسم المنتج");
            d.addColumn("الكمية أو العدد");
            d.addColumn("سعر الوحدة");
            d.addColumn("القيمة الأجمالية");
            
            //q1="Select product_name ,price from store where id ="
            ResultSet r;
            while(rs.next()){
                stmt2 = conn1.createStatement();
                q1="Select product_name ,price from store where id ="+rs.getInt("product_id")+" LIMIT 1";
                r =stmt2.executeQuery(q1);
                if(r.next()){
                    try {
                        d.addRow(new Object[]{
                            rs.getInt("product_id"),
                            new String(r.getString("product_name").getBytes(),"UTF-8"),
                            rs.getInt("quantity"),
                            r.getDouble("price"),
                            rs.getDouble("total_cost"),
                        }); } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(ShowInvoice.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
    
            }
            stmt2.close();
            connection.close(conn1);

            }catch (SQLException ex) {
               Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data;
    private javax.swing.JLabel date_time;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jClient;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSeller;
    private javax.swing.JLabel jTotal;
    // End of variables declaration//GEN-END:variables
}
