package king.of.ta3meer;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import king.of.ta3meer.DBConnect;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kamal
 */
public class UpdateProducts extends javax.swing.JFrame {

    public ArrayList<String> brand ;
    public ArrayList<String> country ;
    public ArrayList<String> kinds ;
    public int user_id ;
    public int old_id ;
    public UpdateProducts(ArrayList<String> brand,ArrayList<String> country,ArrayList<String> kinds,int usr,String oldname,String old_price,String old_quantity,String old_country,String old_brand,int old_id,String old_kind) {
        
        this.old_id=old_id;
        this.brand=new ArrayList<>();
        this.brand=brand;
        this.country =new ArrayList<>();
        this.country = country;
        this.kinds =new ArrayList<>();
        this.kinds = kinds;
        this.user_id=usr;

        initComponents();
        for (String kind : this.kinds) {
            this.jKind.addItem(kind);
        }
        for (String coun : this.country) {
            this.jCountry.addItem(coun);
        }
        for (String brd : this.brand) {
            this.jBrand.addItem(brd);
        }
        P_name.setText(oldname);
        Price.setText(old_price);
        Quantity.setText(old_quantity);
        jBrand.setSelectedItem(old_brand);
        jCountry.setSelectedItem(old_country);
        jKind.setSelectedItem(old_kind);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        P_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBrand = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCountry = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jKind = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(142, 128, 106));
        jPanel1.setForeground(new java.awt.Color(255, 230, 188));

        P_name.setBackground(new java.awt.Color(255, 230, 188));
        P_name.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        P_name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        P_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_nameActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(142, 128, 106));
        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 230, 188));
        jLabel1.setText("أسم المنتج");

        jLabel2.setBackground(new java.awt.Color(142, 128, 106));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 230, 188));
        jLabel2.setText("الكمية");

        Quantity.setBackground(new java.awt.Color(255, 230, 188));
        Quantity.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        Quantity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setBackground(new java.awt.Color(142, 128, 106));
        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 230, 188));
        jLabel3.setText("السعر");

        Price.setBackground(new java.awt.Color(255, 230, 188));
        Price.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        Price.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setBackground(new java.awt.Color(142, 128, 106));
        jLabel4.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 230, 188));
        jLabel4.setText("النوع");

        jBrand.setBackground(new java.awt.Color(142, 128, 106));
        jBrand.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jBrand.setForeground(new java.awt.Color(228, 205, 167));
        jBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setBackground(new java.awt.Color(142, 128, 106));
        jLabel5.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 230, 188));
        jLabel5.setText("بلد الصنع");

        jCountry.setBackground(new java.awt.Color(142, 128, 106));
        jCountry.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jCountry.setForeground(new java.awt.Color(228, 205, 167));
        jCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setBackground(new java.awt.Color(142, 128, 106));
        jLabel6.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 230, 188));
        jLabel6.setText("تصنيف");

        jKind.setBackground(new java.awt.Color(142, 128, 106));
        jKind.setFont(new java.awt.Font("Dubai Light", 1, 12)); // NOI18N
        jKind.setForeground(new java.awt.Color(228, 205, 167));
        jKind.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBackground(new java.awt.Color(195, 176, 145));
        jButton1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("تحديث");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jKind, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Price)
                    .addComponent(Quantity)
                    .addComponent(jBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jKind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DBConnect connection = new DBConnect();

        Connection conn1 =connection.connect();//main table
        //Connection conn2 =connection.connect();
        PreparedStatement stmt1;
        Statement stmt2;
        String p_name = P_name.getText();
        float price = Float.valueOf(Price.getText());
        int quantity = Integer.valueOf(Quantity.getText());
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String Dt = formatter.format(date);
        int id = this.user_id;
        int b_id ;
        int c_id;
        int k_id;
        try {
            //geting ids
            stmt2=conn1.createStatement();

            String q1="Select id from brand where brand ='"+jBrand.getSelectedItem()+"'";
            ResultSet rs    = stmt2.executeQuery(q1);

            if(rs.next()){
                b_id= rs.getInt("id");//brand
                //
            }else{
                b_id= jBrand.getSelectedIndex();
            }

            q1="Select id from countries where country_name ='"+jCountry.getSelectedItem()+"'";
            rs    = stmt2.executeQuery(q1);

            if(rs.next()){
                c_id= rs.getInt("id");//country
            }else{
                c_id =jCountry.getSelectedIndex();
            }

            q1="Select id from kinds where kind ='"+jKind.getSelectedItem()+"'";
            rs    = stmt2.executeQuery(q1);

            if(rs.next()){
                k_id= rs.getInt("id");//kind

            }else{
                k_id=jKind.getSelectedIndex();
            }

            //finished getting ids

            //conn1 =connection.connect();
            String query = "Update store set product_name = ?,"
                    + "quantity = ?,"
                    + "price = ?,"
                    + "brand_id = ?,"
                    + "country_id = ? ,"
                    + "Last_update = ?,"
                    + "updatedby_id = ?,"
                    + "kind = ? "
                    + " where id = ?";
            stmt1 = conn1.prepareStatement(query);
            stmt1.setString(1,p_name);
            stmt1.setInt(2, quantity);
            stmt1.setFloat(3, price);
            //to get ids
            stmt1.setInt(4, b_id);
            stmt1.setInt(5, c_id);
            stmt1.setString(6, Dt);
            stmt1.setInt(7,id);//id
            stmt1.setInt(8, k_id);
            stmt1.setInt(9, this.old_id);
            
            stmt1.executeUpdate();
            stmt1.close();
            connection.close(conn1);
            stmt2.close();
            JFrame x = new JFrame();
            x.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(x, "تم التحديث بنجاح أختر عرض مرة أخرى لتشاهد التحديث !");
            
        }catch(Exception e){
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProducts().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P_name;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JComboBox<String> jBrand;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCountry;
    private javax.swing.JComboBox<String> jKind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
